# Generated by Django 5.1.4 on 2025-01-10 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='category',
            field=models.CharField(choices=[('YAC', 'AC'), ('DEL', 'DELUXE')], max_length=3),
        ),
    ]
