# Generated by Django 5.1.4 on 2025-01-11 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_useraccess_admin_only_useraccess_article_create_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='image-default/no-image.png', upload_to='user-profile/'),
        ),
    ]
