# Generated by Django 5.1.4 on 2025-01-11 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0003_alter_product_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='image-default/default-image.png', upload_to='product_image/'),
        ),
    ]
