# Generated by Django 5.1.4 on 2025-01-11 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0004_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='image-default/no-image.png', upload_to='product_image/'),
        ),
    ]
