# Generated by Django 5.1.4 on 2025-01-11 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0006_alter_product_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': (('can_avail_premium_delivery', 'can avail premium delivery on premium products'), ('cann_add_premium_discount', 'can avail more premium discount on premium products'))},
        ),
    ]
